stages:
  - check_issues

check_issue_template:
  stage: check_issues
  image: python:3.8
  tags: [Linux]
  script:
    - pip install python-gitlab
    - python check_issues.py
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
